function [ notAllowed ] = isNotAllowedVesselPosition( cancervariable,randomgridposition,lcv_vesselposition )
%UNTITLED6 Summary of this function goes here
%   Detailed explanation goes here

N = cancervariable.matrixrownumber;
M = cancervariable.matrixcolnumber;

notAllowed = (cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1)-1,N),coord(randomgridposition(lcv_vesselposition,2),M)) ~= 1 ...
           && (cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1)-2,N),coord(randomgridposition(lcv_vesselposition,2),M)) == 1 ...
           || cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1)-1,N),coord(randomgridposition(lcv_vesselposition,2)-1,M)) == 1 ...
           || cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1)-1,N),coord(randomgridposition(lcv_vesselposition,2)+1,M)) == 1)) ...
           || ...
           (cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1),N),coord(randomgridposition(lcv_vesselposition,2)-1,M)) ~=1 ...
           && (cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1)-1,N),coord(randomgridposition(lcv_vesselposition,2)-1,M)) == 1 ...
           || cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1),N),coord(randomgridposition(lcv_vesselposition,2)-2,M)) == 1 ...
           || cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1)+1,N),coord(randomgridposition(lcv_vesselposition,2)-1,M)) == 1)) ...
           || ...
           (cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1),N),coord(randomgridposition(lcv_vesselposition,2)+1,M)) ~=1 ...
           && (cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1)-1,N),coord(randomgridposition(lcv_vesselposition,2)+1,M)) == 1 ...
           || cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1),N),coord(randomgridposition(lcv_vesselposition,2)+2,M)) == 1 ...
           || cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1)+1,N),coord(randomgridposition(lcv_vesselposition,2)+1,M)) == 1)) ...
           || ...
           (cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1)+1,N),coord(randomgridposition(lcv_vesselposition,2),M)) ~=1 ...
           && (cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1)+1,N),coord(randomgridposition(lcv_vesselposition,2)-1,M)) == 1 ...
           || cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1)+2,N),coord(randomgridposition(lcv_vesselposition,2),M)) == 1 ...
           || cancervariable.statematrix(coord(randomgridposition(lcv_vesselposition,1)+1,N),coord(randomgridposition(lcv_vesselposition,2)+1,M)) == 1)) ...
           || ...
           cancervariable.statematrix(randomgridposition(lcv_vesselposition,1),randomgridposition(lcv_vesselposition,2)) == 1;
end

